# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: pwd
    - name: Build with Gradle
      run: pwd
  #  - name: Change File name
  #    run: |
  #      mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk      
  #  - uses: actions/upload-artifact@v2
  #    with:
  #      name: crafting-dead
  #      path: |
  #        ./crafting-dead-core/build/libs/*.jar
  #        ./crafting-dead-immerse/build/libs/*.jar
  #        ./crafting-dead-survival/build/libs/*.jar
